# Generated by Django 5.2.5 on 2025-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dir', models.CharField(max_length=350)),
                ('id_par', models.IntegerField()),
                ('id_uni', models.IntegerField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_est', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_est', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_mun', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mun', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_par', models.AutoField(primary_key=True, serialize=False)),
                ('nom_par', models.TextField()),
            ],
            options={
                'db_table': 'parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_uni', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_uni', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'universidad',
                'managed': False,
            },
        ),
    ]
