# Generated by Django 3.2.19 on 2025-08-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dir', models.CharField(max_length=350)),
                ('id_par', models.IntegerField()),
                ('id_uni', models.IntegerField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_est', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_est', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_mun', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mun', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_par', models.AutoField(primary_key=True, serialize=False)),
                ('nom_par', models.TextField()),
            ],
            options={
                'db_table': 'parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_uni', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_uni', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'universidad',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='becario_internacional_en_venezuela',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='becario_venezolano_en_exterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='becario_venezolano_en_venezuela',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='carrera_cursada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='idiomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='ocupacion_actual',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='tipo_beca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='titularidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.estado'),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.municipio'),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.parroquia'),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.universidad'),
        ),
    ]
