# Generated by Django 3.2.19 on 2025-08-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_formulario', '0002_direccion_djangomigrations_estado_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaregistro',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.estado'),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.municipio'),
        ),
        migrations.AddField(
            model_name='personaregistro',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.parroquia'),
        ),
    ]
