# Generated by Django 3.2.19 on 2025-08-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_formulario', '0003_auto_20250808_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaregistro',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='app_formulario.universidad'),
        ),
    ]
